title: Senescience
description: > # this means to ignore newlines until "baseurl:"
  The ageing blog.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://senescience.tk" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Senescience # add your name
author-img: senescience-white.png # add your photo
about-author: A blog about ageing. # add description
twitter: senescience # add your Twitter handle
facebook: senescience # add your Facebook handle
github: senescience # add your Github handle
linkedin: senescience # add your Linkedin handle
email: senescience # add your Email address

# Disqus
discus-identifier: senescience # add your discus identifier
comments: true

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
