title: Senescience
description: > # this means to ignore newlines until "baseurl:"
  Description. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Senescience # add your name
author-img: logo.png # add your photo
about-author: The ageing blog. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: senescience # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
